Update build.rs
broxus/nekoton_bridge pull request #30
Opened 2023-03-16 12:39 UTC by 0xdeafbeef

2023-03-16 15:15 UTC, nesquikm requested changes
@0xdeafbeef thnx :)

2023-03-16 15:23 UTC, Alex-A4 commented
Why we need this changes?

2023-03-16 15:39 UTC, nesquikm commented
> Why we need this changes?

I think in order to verbose report errors and create paths more correctly (CARGO_MANIFEST_DIR). Am I right? :)

2023-03-20 11:50 UTC, nesquikm commented on packages/nekoton_bridge/native/build.rs
> +        .join("src/merged.rs")
@0xdeafbeef ping?

2023-03-21 09:03 UTC, closed without merging