Feat/transfer transport logic
broxus/nekoton_bridge pull request #35
Opened 2023-03-17 12:47 UTC by Alex-A4

- Implemented rust & dart side transport

2023-03-17 14:05 UTC, nesquikm requested changes

2023-03-17 14:05 UTC, nesquikm commented on packages/flutter_nekoton_bridge/lib/nekoton/transport/transport_lib.dart
> +export 'jrpc_transport.dart';
Empty line on EOF

2023-03-17 15:58 UTC, Alex-A4 commented on packages/flutter_nekoton_bridge/lib/nekoton/transport/transport_lib.dart
> +export 'jrpc_transport.dart';
-

2023-03-19 07:59 UTC, nesquikm approved these changes

2023-03-19 09:45 UTC, merged